0001  const app=document.getElementById("app");
0002  const ASSETS={
0003    frontpage:"assets/frontpage/frontpage.PNG",casefile:"assets/casefile/casefile.PNG",investigation:"assets/investigation/investigation.jpg",caseclosed:"assets/caseclosed/caseclosed.PNG"}
0004    ;
0005    const CARDS={
0006      suspects:[["india_gold","India Gold","assets/suspects/India_gold.JPG",["female","wealthy","glamorous","ambitious","connected","secretive","status","observant"]],["bianca_frost","Bianca Frost","assets/suspects/bianca_frost.JPG",["female","glasses","wealthy","influential","secretive","ambitious","status","observant"]],["cleo_saint","Cleo Saint","assets/suspects/cleo_saint.JPG",["female","tattooed","creative","disciplined","glamorous","secretive","ambitious","volatile"]],["dorian_luxe","Dorian Luxe","assets/suspects/dorian_luxe.JPG",["male","wealthy","influential","secretive","ambitious","status","collector","observant"]],["gideon_pryce","Gideon Pryce","assets/suspects/gideon_pryce.JPG",["male","wealthy","disciplined","secretive","strategic","cold","status","observant"]],["harvey_slate","Harvey Slate","assets/suspects/harvey_slate.JPG",["male","wealthy","influential","observant","ambitious","public","status","secretive"]],["jaxon_vale","Jaxon Vale","assets/suspects/jaxon_vale.JPG",["male","creative","tech","charismatic","reckless","public","ambitious","volatile"]],["milo_vale","Milo Vale","assets/suspects/milo-vale.JPG",["male","tech","intelligent","secretive","young","opportunistic","quiet","observant"]],["nova_wilde","Nova Wilde","assets/suspects/nova_wilde.JPG",["female","creative","glamorous","secretive","public","ambitious","volatile","stylish"]],["otis_blank","Otis Blank","assets/suspects/otis_blank.JPG",["male","quiet","observant","technical","private","nervous","secretive","disciplined"]],["piper_bloom","Piper Bloom","assets/suspects/piper_bloom.JPG",["female","social","romantic","glamorous","impulsive","public","stylish","secretive"]],["rex_branson","Rex Branson","assets/suspects/rex_branson.JPG",["male","athletic","aggressive","wealthy","volatile","status","public","ambitious"]],["saffron_skye","Saffron Skye","assets/suspects/saffron_skye.JPG",["female","creative","public","ambitious","stylish","secretive","glamorous","volatile"]],["sebastian_drift","Sebastian Drift","assets/suspects/sebastian_drift.JPG",["male","wealthy","romantic","obsessive","public","vain","status","glamorous"]],["tilly_chrome","Tilly Chrome","assets/suspects/tilly_chrome.JPG",["female","creative","disciplined","ideological","intense","professional","tattooed","observant"]],["velvet_kane","Velvet Kane","assets/suspects/velvet_kane.JPG",["female","intelligent","ethical","legal","observant","professional","glasses","secretive"]]],
0007      rooms:[["art_vault","Art Vault","assets/rooms/art_vault.jpg",["restricted","private","valuable","quiet","locked","luxury","surveillance","after-hours"]],["billiard_room","Billiard Room","assets/rooms/billiard_room.jpg",["recreational","private","quiet","after-hours","social","low-light","soft","luxury"]],["chefs_table","Chef's Table","assets/rooms/chefs_table.jpg",["food","private","luxury","booked","staffed","social","water","after-hours"]],["cinema","Cinema","assets/rooms/cinema.jpg",["dark","soundproof","screen","private","recreational","seated","low-light","soft"]],["dressing","Dressing Room","assets/rooms/dressing.jpg",["private","mirrors","fashion","quiet","restricted","personal","soft","after-hours"]],["rooftop","Rooftop","assets/rooms/rooftop.jpg",["isolated","open-air","high","night","private","restricted","wind","low-light"]],["gym","Gym","assets/rooms/gym.jpg",["wellness","equipment","physical","private","mirrors","after-hours","open","surveillance"]],["kitchen","Smart Kitchen","assets/rooms/kitchen.jpg",["food","tech","water","screen","staffed","private","dining","surveillance"]],["library","Library","assets/rooms/library.jpg",["quiet","knowledge","private","soft","night","prestige","restricted","valuable"]],["lift","Lift","assets/rooms/lift.jpg",["restricted","movement","small","sealed","tech","transit","surveillance","locked"]],["med_suite","Medical Suite","assets/rooms/med-suite.jpg",["medical","restricted","clean","private","equipment","quiet","locked","water"]],["observ","Observatory","assets/rooms/observ.jpg",["isolated","high","tech","quiet","night","restricted","screen","private"]],["panic","Panic Room","assets/rooms/panic.jpg",["locked","secure","hidden","restricted","small","private","surveillance","sealed"]],["podstudio","Podcast Studio","assets/rooms/podstudio.jpg",["soundproof","tech","screen","creative","private","recording","low-light","sealed"]],["pool","Pool","assets/rooms/pool.jpg",["water","wellness","recreational","open","luxury","night","quiet","private"]],["wine_cellar","Wine Cellar","assets/rooms/wine_cellar.jpg",["luxury","restricted","quiet","valuable","private","cold","after-hours","locked"]]],
0008      weapons:[["champagne_sabre","Champagne Sabre","assets/weapons/champagne_sabre.png",["sharp","luxury","ceremonial","metal","collectible","handheld","decorative","fingerprintable"]],["chargeing_cable","Charging Cable","assets/weapons/chargeing_cable.png",["flexible","tech","everyday","concealable","cord","modern","wired","small"]],["chefs_knife","Chef's Knife","assets/weapons/chefs_knife.png",["sharp","kitchen","metal","professional","handheld","practical","fingerprintable","obvious"]],["crystal_award","Crystal Award","assets/weapons/crystal_award.PNG",["blunt","fragile","decorative","luxury","heavy","collectible","fingerprintable","office"]],["drone","Drone","assets/weapons/drone.png",["tech","remote","surveillance","modern","powered","mobile","black","fragile"]],["gold_dumbbell","Gold Dumbbell","assets/weapons/gold_dumbbell.png",["blunt","heavy","luxury","gym","metal","obvious","fingerprintable","decorative"]],["keycard","Keycard","assets/weapons/keycard.png",["access","tech","thin","corporate","concealable","plastic","small","everyday"]],["luxury_pen","Luxury Pen","assets/weapons/luxury_pen.png",["sharp","luxury","small","concealable","professional","metal","office","fingerprintable"]],["mangrenade_candle","Mangrenade Candle","assets/weapons/mangreneade_candle.png",["fire","brand","collectible","decorative","small","luxury","everyday","fragile"]],["marble_bust","Marble Bust","assets/weapons/marble_bust.PNG",["blunt","heavy","decorative","luxury","art","solid","fingerprintable","office"]],["mci_original_artwork","MCI Original Artwork","assets/weapons/mci_original_artwork.PNG",["collectible","art","decorative","valuable","fragile","brand","luxury","office"]],["ring_light_stand","Ring Light Stand","assets/weapons/ring_light_stand.png",["metal","creative","tech","long","studio","portable","fingerprintable","blunt"]],["smart_speaker","Smart Speaker","assets/weapons/smart_speaker.png",["tech","powered","black","blunt","small","wired","everyday","office"]],["smart_watch_cable","Smart Watch Cable","assets/weapons/smart_watch_cable.png",["tech","flexible","small","everyday","concealable","cord","wired","modern"]],["sous_vide_weight","Sous Vide Weight","assets/weapons/sous_vide_weight.png",["heavy","kitchen","metal","blunt","professional","small","fingerprintable","practical"]],["stiletto","Stiletto","assets/weapons/stiletto.png",["sharp","fashion","concealable","luxury","personal","handheld","small","fingerprintable"]],["vr_headset","VR Headset","assets/weapons/vr_headset.png",["tech","modern","black","recreational","powered","headset","fragile","everyday"]]],
0009      motives:[["affair","Affair","assets/motives/affair.png",["romantic","secret","personal","impulsive","status","emotional","shame","risk"]],["blackmail","Blackmail","assets/motives/blackmail.png",["secret","control","planned","fear","money","leverage","long-term","corporate"]],["career","Career","assets/motives/career.png",["professional","ambition","status","planned","reputation","competitive","long-term","public"]],["cover_up","Cover Up","assets/motives/cover_up.png",["secret","planned","protective","corporate","fear","control","reputation","long-term"]],["debt_pressure","Debt Pressure","assets/motives/debt_pressure.png",["financial","desperate","pressure","fear","short-term","risk","long-term","control"]],["family_secret","Family Secret","assets/motives/family_secret.png",["family","secret","protective","long-term","shame","emotional","reputation","fear"]],["financial_ruin","Financial Ruin","assets/motives/financial_ruin.png",["financial","desperate","status","fear","collapse","planned","public","reputation"]],["inheritance","Inheritance","assets/motives/inheritance.png",["family","financial","planned","status","long-term","greed","secret","control"]],["jealousy","Jealousy","assets/motives/jealousy.png",["romantic","emotional","impulsive","status","personal","resentment","public","shame"]],["mistaken_id","Mistaken Identity","assets/motives/mistaken_id.png",["error","confusion","impulsive","bad intel","accidental","opportunistic","fear","short-term"]],["obsession","Obsession","assets/motives/obsession.png",["romantic","fixated","emotional","long-term","irrational","personal","secret","control"]],["professional_rivalry","Professional Rivalry","assets/motives/professional_rivalry.png",["professional","status","competition","ambition","reputation","planned","long-term","public"]],["rejection","Rejection","assets/motives/rejection.png",["romantic","emotional","impulsive","personal","humiliation","resentment","status","shame"]],["reputation_protection","Reputation Protection","assets/motives/reputation_protection.png",["status","reputation","protective","planned","public","fear","professional","control"]],["revenge","Revenge","assets/motives/revenge.png",["resentment","justice","planned","personal","long-term","emotional","secret","control"]],["whistleblower_silence","Whistleblower Silence","assets/motives/whistleblower_silence.png",["corporate","secret","planned","protective","reputation","fear","professional","control"]]]}
0010      ;
0011      const CASES=[{
0012        id:"MCI-001",victim:"Velvet Kane",victimImg:"assets/suspects/velvet_kane.JPG",title:"The Better Model",turns:6,solution:{
0013          suspect:"dorian_luxe",weapon:"marble_bust",room:"art_vault",motive:"professional_rivalry"}
0014          ,brief:"Velvet Kane has been found dead inside Blackwood Tower. Evidence suggests a confrontation took place shortly before her death. Identify the murderer, weapon, room and motive.",den:"Dorian Luxe murdered Velvet Kane. The confrontation took place inside the Art Vault. During the argument Dorian used the Marble Bust as an improvised weapon. The motive was Professional Rivalry."}
0015          ,{
0016            id:"MCI-002",victim:"Otis Blank",victimImg:"assets/suspects/otis_blank.JPG",title:"Dead Air",turns:6,solution:{
0017              suspect:"milo_vale",weapon:"smart_speaker",room:"podstudio",motive:"cover_up"}
0018              ,brief:"Otis Blank has been found dead after hours inside Blackwood Tower. The first report mentions locked doors, recorded audio and a technical system that should not have been running.",den:"Milo Vale murdered Otis Blank in the Podcast Studio. The Smart Speaker was used as part of the method. The motive was Cover Up. Otis knew too much and Milo chose silence over exposure."}
0019              ,{
0020                id:"MCI-003",victim:"India Gold",victimImg:"assets/suspects/India_gold.JPG",title:"A View From Above",turns:6,solution:{
0021                  suspect:"saffron_skye",weapon:"champagne_sabre",room:"rooftop",motive:"blackmail"}
0022                  ,brief:"India Gold has been found dead at Blackwood Tower. Witness statements place several residents near the upper floors shortly before midnight. The evidence points to leverage, fear and a private confrontation.",den:"Saffron Skye murdered India Gold on the Rooftop using the Champagne Sabre. India had information Saffron could not allow to surface. The motive was Blackmail."}
0023                  ];
0024                  let state={
0025                    screen:"home",caseIndex:0,guessesLeft:6,selected:{
0026                    }
0027                    ,locked:{
0028                    }
0029                    ,wrong:{
0030                    }
0031                    ,revealed:{
0032                    }
0033                    ,evidence:{
0034                      suspect:[],weapon:[],room:[],motive:[]}
0035                      ,feedback:[],history:[],lastScore:null}
0036                      ;
0037                      let scrollMemory={
0038                      }
0039                      ;
0040                      const player={
0041                        rank:localStorage.getItem("mci_rank")||"Detective",streak:+(localStorage.getItem("mci_streak")||0),solved:+(localStorage.getItem("mci_solved")||0)}
0042                        ;
0043                        const currentCase=()=>CASES[state.caseIndex];
0044                        function haptic(p=10){
0045                          if(navigator.vibrate)navigator.vibrate(p)}
0046                          function bg(p){
0047                            return `style="background-image:url('${p}')"`}
0048                            function saveScrolls(){
0049                              document.querySelectorAll(".carousel").forEach(e=>scrollMemory[e.dataset.type]=e.scrollLeft)}
0050                              function restoreScrolls(){
0051                                requestAnimationFrame(()=>document.querySelectorAll(".carousel").forEach(e=>{
0052                                  if(scrollMemory[e.dataset.type]!=null)e.scrollLeft=scrollMemory[e.dataset.type];
0053                                  if(state.selected[e.dataset.type]){
0054                                    const c=e.querySelector(`[data-card-id="${state.selected[e.dataset.type]}"]`);
0055                                    if(c)c.scrollIntoView({
0056                                      inline:"center",block:"nearest",behavior:"smooth"}
0057                                      )}
0058                                    }
0059                                    ))}
0060                                    function updateLiveCards(){
0061                                      document.querySelectorAll(".carousel").forEach(car=>{
0062                                        const mid=car.getBoundingClientRect().left+car.clientWidth/2;
0063                                        let best=null,dist=Infinity;
0064                                        car.querySelectorAll(".card").forEach(card=>{
0065                                          card.classList.remove("live");
0066                                          const r=card.getBoundingClientRect();
0067                                          const d=Math.abs((r.left+r.width/2)-mid);
0068                                          if(d<dist){
0069                                            dist=d;
0070                                            best=card}
0071                                          }
0072                                          );
0073                                          if(best)best.classList.add("live")}
0074                                          )}
0075                                          function render(){
0076                                            saveScrolls();
0077                                            if(state.screen==="home")home();
0078                                            if(state.screen==="casefile")casefile();
0079                                            if(state.screen==="investigation")investigation();
0080                                            if(state.screen==="solved")end(false);
0081                                            if(state.screen==="failed")end(true);
0082                                            restoreScrolls()}
0083                                            function home(){
0084                                              app.innerHTML=`<section class="screen" ${bg(ASSETS.frontpage)}><div class="content"><h1>MCI</h1><h2>MURDER CASE INVESTIGATION</h2><div class="statgrid"><div class="stat"><div class="label">Rank</div><div class="value">${player.rank}</div></div><div class="stat"><div class="label">Streak</div><div class="value">${player.streak}</div></div><div class="stat"><div class="label">Solved</div><div class="value">${player.solved}</div></div></div><div class="panel"><h2>MVP DAILY FLOW</h2><div class="case-list">${CASES.map((c,i)=>`<div class="case-pill ${i<state.caseIndex?'done':''}"><b>${
0085                                                c.id}
0086                                                </b><br>${
0087                                                  c.title}
0088                                                  </div>`).join("")}</div></div><button class="primary" onclick="openCase()">OPEN CASE FILE</button><button class="secondary" onclick="alert('Information Base comes next')">INFORMATION BASE</button></div></section>`}
0089                                                  function openCase(){
0090                                                    resetForCase(state.caseIndex);
0091                                                    go("casefile")}
0092                                                    function resetForCase(i){
0093                                                      state={
0094                                                        ...state,caseIndex:i,guessesLeft:CASES[i].turns,selected:{
0095                                                        }
0096                                                        ,locked:{
0097                                                        }
0098                                                        ,wrong:{
0099                                                        }
0100                                                        ,revealed:{
0101                                                        }
0102                                                        ,evidence:{
0103                                                          suspect:[],weapon:[],room:[],motive:[]}
0104                                                          ,feedback:[],history:[],lastScore:null}
0105                                                          ;
0106                                                          scrollMemory={
0107                                                          }
0108                                                        }
0109                                                        function casefile(){
0110                                                          const c=currentCase();
0111                                                          app.innerHTML=`<section class="screen" ${bg(ASSETS.casefile)}><div class="content"><div class="panel"><h2>VICTIM FILE OPENED</h2><h2>${c.victim}</h2><h3>${c.id} — ${c.title}</h3><p>${c.brief}</p><h2>${c.turns} accusations authorised</h2></div><button class="primary" onclick="go('investigation')">BEGIN INVESTIGATION</button></div></section>`}
0112                                                          function investigation(){
0113                                                            const c=currentCase();
0114                                                            app.innerHTML=`<div class="fixedhud"><div class="hudrow"><div>${player.rank}</div><div>${c.id}</div><div>${state.guessesLeft} left</div></div><div class="theory">Murderer: ${name("suspects",state.selected.suspect)} | Weapon: ${name("weapons",state.selected.weapon)} | Room: ${name("rooms",state.selected.room)} | Motive: ${name("motives",state.selected.motive)} | ${Object.keys(state.locked).length}/4 locked</div></div><section class="screen investigation" ${bg(ASSETS.investigation)}><div class="content">${progressHTML()}${evidenceBoard()}${carousel("suspect","MURDERER",CARDS.suspects)}${carousel("weapon","WEAPON",CARDS.weapons)}${carousel("room","ROOM",CARDS.rooms)}${carousel("motive","MOTIVE",CARDS.motives)}${feedbackHTML()}<div class="panel"><h2>MAKE ACCUSATION</h2><p>Select one murderer, weapon, room and motive.</p><button class="primary" onclick="accuse()">SUBMIT ACCUSATION</button></div></div></section>`;
0115                                                            setTimeout(updateLiveCards,50)}
0116                                                            function evidenceBoard(){
0117                                                              const labels={
0118                                                                suspect:"CHARACTERISTICS",weapon:"WEAPON FEATURES",room:"ROOM FEATURES",motive:"DRIVERS"}
0119                                                                ;
0120                                                                return `<div class="panel"><h2>EVIDENCE BOARD</h2><div class="evidence-board">${["suspect","weapon","room","motive"].map(k=>`<div class="evidence-box"><h4>${
0121                                                                  labels[k]}
0122                                                                  </h4>${
0123                                                                    state.evidence[k].length?state.evidence[k].map(x=>`<span class="evidence-tag">${x}</span>`).join(""):"<span class='evidence-tag'>Awaiting evidence</span>"}
0124                                                                    </div>`).join("")}</div></div>`}
0125                                                                    function progressHTML(){
0126                                                                      if(!state.lastScore)return "";
0127                                                                      const pct=[0,25,50,75,100][state.lastScore];
0128                                                                      const col=["var(--red)","var(--amber1)","var(--amber2)","var(--amber3)","var(--green)"][state.lastScore];
0129                                                                      return `<div class="panel"><div class="progress-label">${state.lastScore}/4 CATEGORIES MATCH</div><div class="progress-shell"><div class="progress-bar" style="width:${pct}%;background:${col}"></div></div></div>`}
0130                                                                      function carousel(type,title,items){
0131                                                                        const loop=[...items,...items,...items];
0132                                                                        return `<div class="carousel-block"><div class="carousel-title">${title}</div><div class="carousel" data-type="${type}" onscroll="loopCarousel(this);updateLiveCards()">${loop.map(item=>card(type,item)).join("")}</div></div>`}
0133                                                                        function card(type,item){
0134                                                                          const[id,n,img,traits]=item;
0135                                                                          const cls=[state.selected[type]===id?"selected":"",state.locked[type]===id?"correct":"",state.wrong[type]?.includes(id)?"incorrect":""].join(" ");
0136                                                                          const contain=id==="marble_bust"?"contain":"";
0137                                                                          return `<div class="card ${cls}" data-card-id="${id}" onclick="selectCard('${type}','${id}')"><img class="${contain}" src="${img}" onerror="this.style.opacity=.15"><div class="card-name">${n}</div><div class="traits">${traits.slice(0,8).map(t=>`<span class="trait ${isRev(type,id,t)?"revealed":""}">${
0138                                                                            t}
0139                                                                            </span>`).join("")}</div></div>`}
0140                                                                            function selectCard(type,id){
0141                                                                              if(state.locked[type])return;
0142                                                                              haptic(10);
0143                                                                              state.selected[type]=id;
0144                                                                              render()}
0145                                                                              function accuse(){
0146                                                                                const keys=["suspect","weapon","room","motive"],c=currentCase();
0147                                                                                if(!keys.every(k=>state.selected[k])){
0148                                                                                  haptic([20,50,20]);
0149                                                                                  alert("Select one murderer, weapon, room and motive.");
0150                                                                                  return}
0151                                                                                  haptic(25);
0152                                                                                  state.feedback=[];
0153                                                                                  let correct=0;
0154                                                                                  const row=[];
0155                                                                                  keys.forEach(k=>{
0156                                                                                    const guess=state.selected[k],sol=c.solution[k],ok=guess===sol;
0157                                                                                    row.push(ok);
0158                                                                                    if(ok)correct++;
0159                                                                                    if(ok){
0160                                                                                      state.locked[k]=guess;
0161                                                                                      state.feedback.push({
0162                                                                                        type:k,ok:true,name:item(k,guess)[1]}
0163                                                                                        );
0164                                                                                        haptic([25,45,25])}
0165                                                                                        else{
0166                                                                                          state.wrong[k]=state.wrong[k]||[];
0167                                                                                          if(!state.wrong[k].includes(guess))state.wrong[k].push(guess);
0168                                                                                          const matches=item(k,guess)[3].filter(t=>item(k,sol)[3].includes(t));
0169                                                                                          const disclosed=matches[0]||"none";
0170                                                                                          state.revealed[k]=state.revealed[k]||{
0171                                                                                          }
0172                                                                                          ;
0173                                                                                          state.revealed[k][guess]=state.revealed[k][guess]||[];
0174                                                                                          if(disclosed!=="none"&&!state.revealed[k][guess].includes(disclosed))state.revealed[k][guess].push(disclosed);
0175                                                                                          if(disclosed!=="none"&&!state.evidence[k].includes(disclosed))state.evidence[k].push(disclosed);
0176                                                                                          state.feedback.push({
0177                                                                                            type:k,ok:false,name:item(k,guess)[1],disclosed,hidden:Math.max(matches.length-(matches.length?1:0),0)}
0178                                                                                            )}
0179                                                                                          }
0180                                                                                          );
0181                                                                                          state.history.push(row);
0182                                                                                          state.lastScore=correct;
0183                                                                                          state.guessesLeft--;
0184                                                                                          if(correct===4){
0185                                                                                            player.solved++;
0186                                                                                            player.streak++;
0187                                                                                            localStorage.setItem("mci_solved",player.solved);
0188                                                                                            localStorage.setItem("mci_streak",player.streak);
0189                                                                                            haptic([60,90,60]);
0190                                                                                            go("solved");
0191                                                                                            return}
0192                                                                                            if(state.guessesLeft<=0){
0193                                                                                              haptic([100,100,100]);
0194                                                                                              go("failed");
0195                                                                                              return}
0196                                                                                              render()}
0197                                                                                              function feedbackHTML(){
0198                                                                                                if(!state.feedback.length)return"";
0199                                                                                                return `<div class="panel"><h2>EVIDENCE FEEDBACK</h2>${state.feedback.map(f=>{if(f.ok)return `<div class="feedback-card correct"><h3>${
0200                                                                                                  f.type.toUpperCase()}
0201                                                                                                  </h3><p>${
0202                                                                                                    f.name}
0203                                                                                                    </p><p class="green">CONFIRMED</p></div>`;const w=f.type==="suspect"?"characteristic":f.type==="motive"?"driver":"feature";return `<div class="feedback-card"><h3>${
0204                                                                                                      f.type.toUpperCase()}
0205                                                                                                      </h3><p>${
0206                                                                                                        f.name}
0207                                                                                                        </p><p class="green">${
0208                                                                                                          f.disclosed}
0209                                                                                                          </p><p>${
0210                                                                                                            f.hidden}
0211                                                                                                            additional ${
0212                                                                                                              w}
0213                                                                                                              ${
0214                                                                                                                f.hidden===1?"":"s"}
0215                                                                                                                match.</p></div>`}).join("")}</div>`}
0216                                                                                                                function end(failed){
0217                                                                                                                  const c=currentCase(),s=c.solution;
0218                                                                                                                  app.innerHTML=`<section class="screen" ${bg(ASSETS.caseclosed)}><div class="content"><div class="end-title">${failed?"THEY GOT AWAY WITH IT":"CASE SOLVED"}</div><div class="subtitle">${failed?"The killer walks free.":"Great work, Detective."}</div><div class="panel"><h2>VICTIM: ${c.victim}</h2><div class="result-grid">${res("MURDERER","suspect",s.suspect)}${res("WEAPON","weapon",s.weapon)}${res("ROOM","room",s.room)}${res("MOTIVE","motive",s.motive)}</div><h2>RECONSTRUCTION</h2><p>${highlight(c.den)}</p><button class="primary" onclick="share(${failed})">SHARE RESULT</button>${state.caseIndex<CASES.length-1?`<button class="secondary" onclick="nextCase()">NEXT MVP DAY</button>`:`<button class="secondary" onclick="go('home')">RETURN HOME</button>`}</div></div></section>`}
0219                                                                                                                  function res(label,type,id){
0220                                                                                                                    const it=item(type,id);
0221                                                                                                                    return `<div class="result-card"><img class="${id==="marble_bust"?"contain":""}" src="${it[2]}"><h2>${label}</h2><p>${it[1]}</p></div>`}
0222                                                                                                                    function highlight(txt){
0223                                                                                                                      const c=currentCase(),s=c.solution;
0224                                                                                                                      [item("suspect",s.suspect)[1],item("weapon",s.weapon)[1],item("room",s.room)[1],item("motive",s.motive)[1]].forEach(w=>{
0225                                                                                                                        txt=txt.replaceAll(w,`<mark>${w}</mark>`)}
0226                                                                                                                        );
0227                                                                                                                        return txt}
0228                                                                                                                        function share(failed){
0229                                                                                                                          const c=currentCase(),used=c.turns-state.guessesLeft,grid=state.history.map(r=>r.map(x=>x?"🟩":"⬛").join("")).join("\n")||"⬛⬛⬛⬛";
0230                                                                                                                          const text=`${c.id}\n\n${grid}\n\n${failed?"They got away with it.":`Solved in ${
0231                                                                                                                            used}
0232                                                                                                                            accusation${
0233                                                                                                                              used===1?"":"s"}
0234                                                                                                                              .`}\nRank: ${player.rank}\nhttps://mancave-industries.github.io/MCI_Muder_Case_Investigation-/`;
0235                                                                                                                              if(navigator.share)navigator.share({
0236                                                                                                                                text}
0237                                                                                                                                );
0238                                                                                                                                else{
0239                                                                                                                                  navigator.clipboard.writeText(text);
0240                                                                                                                                  alert("Result copied.")}
0241                                                                                                                                }
0242                                                                                                                                function nextCase(){
0243                                                                                                                                  state.caseIndex++;
0244                                                                                                                                  resetForCase(state.caseIndex);
0245                                                                                                                                  go("casefile")}
0246                                                                                                                                  function go(x){
0247                                                                                                                                    state.screen=x;
0248                                                                                                                                    render()}
0249                                                                                                                                    function item(type,id){
0250                                                                                                                                      return({
0251                                                                                                                                        suspect:CARDS.suspects,weapon:CARDS.weapons,room:CARDS.rooms,motive:CARDS.motives}
0252                                                                                                                                        [type]).find(x=>x[0]===id)}
0253                                                                                                                                        function name(group,id){
0254                                                                                                                                          if(!id)return"Not selected";
0255                                                                                                                                          return({
0256                                                                                                                                            suspects:CARDS.suspects,weapons:CARDS.weapons,rooms:CARDS.rooms,motives:CARDS.motives}
0257                                                                                                                                            [group]).find(x=>x[0]===id)?.[1]||"Not selected"}
0258                                                                                                                                            function isRev(type,id,t){
0259                                                                                                                                              return state.revealed?.[type]?.[id]?.includes(t)}
0260                                                                                                                                              function loopCarousel(el){
0261                                                                                                                                                const third=el.scrollWidth/3;
0262                                                                                                                                                if(el.scrollLeft<third*.25)el.scrollLeft+=third;
0263                                                                                                                                                if(el.scrollLeft>third*1.75)el.scrollLeft-=third;
0264                                                                                                                                                scrollMemory[el.dataset.type]=el.scrollLeft}
0265                                                                                                                                                render();
const app=document.getElementById("app");
const ASSETS={frontpage:"assets/frontpage/frontpage.PNG",casefile:"assets/casefile/casefile.PNG",investigation:"assets/investigation/investigation.jpg",caseclosed:"assets/caseclosed/caseclosed.PNG"};
const CARDS={
suspects:[["india_gold","India Gold","assets/suspects/India_gold.JPG",["female","wealthy","glamorous","ambitious","connected","secretive","status","observant"]],["bianca_frost","Bianca Frost","assets/suspects/bianca_frost.JPG",["female","glasses","wealthy","influential","secretive","ambitious","status","observant"]],["cleo_saint","Cleo Saint","assets/suspects/cleo_saint.JPG",["female","tattooed","creative","disciplined","glamorous","secretive","ambitious","volatile"]],["dorian_luxe","Dorian Luxe","assets/suspects/dorian_luxe.JPG",["male","wealthy","influential","secretive","ambitious","status","collector","observant"]],["gideon_pryce","Gideon Pryce","assets/suspects/gideon_pryce.JPG",["male","wealthy","disciplined","secretive","strategic","cold","status","observant"]],["harvey_slate","Harvey Slate","assets/suspects/harvey_slate.JPG",["male","wealthy","influential","observant","ambitious","public","status","secretive"]],["jaxon_vale","Jaxon Vale","assets/suspects/jaxon_vale.JPG",["male","creative","tech","charismatic","reckless","public","ambitious","volatile"]],["milo_vale","Milo Vale","assets/suspects/milo-vale.JPG",["male","tech","intelligent","secretive","young","opportunistic","quiet","observant"]],["nova_wilde","Nova Wilde","assets/suspects/nova_wilde.JPG",["female","creative","glamorous","secretive","public","ambitious","volatile","stylish"]],["otis_blank","Otis Blank","assets/suspects/otis_blank.JPG",["male","quiet","observant","technical","private","nervous","secretive","disciplined"]],["piper_bloom","Piper Bloom","assets/suspects/piper_bloom.JPG",["female","social","romantic","glamorous","impulsive","public","stylish","secretive"]],["rex_branson","Rex Branson","assets/suspects/rex_branson.JPG",["male","athletic","aggressive","wealthy","volatile","status","public","ambitious"]],["saffron_skye","Saffron Skye","assets/suspects/saffron_skye.JPG",["female","creative","public","ambitious","stylish","secretive","glamorous","volatile"]],["sebastian_drift","Sebastian Drift","assets/suspects/sebastian_drift.JPG",["male","wealthy","romantic","obsessive","public","vain","status","glamorous"]],["tilly_chrome","Tilly Chrome","assets/suspects/tilly_chrome.JPG",["female","creative","disciplined","ideological","intense","professional","tattooed","observant"]],["velvet_kane","Velvet Kane","assets/suspects/velvet_kane.JPG",["female","intelligent","ethical","legal","observant","professional","glasses","secretive"]]],
rooms:[["art_vault","Art Vault","assets/rooms/art_vault.jpg",["restricted","private","valuable","quiet","locked","luxury","surveillance","after-hours"]],["billiard_room","Billiard Room","assets/rooms/billiard_room.jpg",["recreational","private","quiet","after-hours","social","low-light","soft","luxury"]],["chefs_table","Chef's Table","assets/rooms/chefs_table.jpg",["food","private","luxury","booked","staffed","social","water","after-hours"]],["cinema","Cinema","assets/rooms/cinema.jpg",["dark","soundproof","screen","private","recreational","seated","low-light","soft"]],["dressing","Dressing Room","assets/rooms/dressing.jpg",["private","mirrors","fashion","quiet","restricted","personal","soft","after-hours"]],["rooftop","Rooftop","assets/rooms/rooftop.jpg",["isolated","open-air","high","night","private","restricted","wind","low-light"]],["gym","Gym","assets/rooms/gym.jpg",["wellness","equipment","physical","private","mirrors","after-hours","open","surveillance"]],["kitchen","Smart Kitchen","assets/rooms/kitchen.jpg",["food","tech","water","screen","staffed","private","dining","surveillance"]],["library","Library","assets/rooms/library.jpg",["quiet","knowledge","private","soft","night","prestige","restricted","valuable"]],["lift","Lift","assets/rooms/lift.jpg",["restricted","movement","small","sealed","tech","transit","surveillance","locked"]],["med_suite","Medical Suite","assets/rooms/med-suite.jpg",["medical","restricted","clean","private","equipment","quiet","locked","water"]],["observ","Observatory","assets/rooms/observ.jpg",["isolated","high","tech","quiet","night","restricted","screen","private"]],["panic","Panic Room","assets/rooms/panic.jpg",["locked","secure","hidden","restricted","small","private","surveillance","sealed"]],["podstudio","Podcast Studio","assets/rooms/podstudio.jpg",["soundproof","tech","screen","creative","private","recording","low-light","sealed"]],["pool","Pool","assets/rooms/pool.jpg",["water","wellness","recreational","open","luxury","night","quiet","private"]],["wine_cellar","Wine Cellar","assets/rooms/wine_cellar.jpg",["luxury","restricted","quiet","valuable","private","cold","after-hours","locked"]]],
weapons:[["champagne_sabre","Champagne Sabre","assets/weapons/champagne_sabre.png",["sharp","luxury","ceremonial","metal","collectible","handheld","decorative","fingerprintable"]],["chargeing_cable","Charging Cable","assets/weapons/chargeing_cable.png",["flexible","tech","everyday","concealable","cord","modern","wired","small"]],["chefs_knife","Chef's Knife","assets/weapons/chefs_knife.png",["sharp","kitchen","metal","professional","handheld","practical","fingerprintable","obvious"]],["crystal_award","Crystal Award","assets/weapons/crystal_award.PNG",["blunt","fragile","decorative","luxury","heavy","collectible","fingerprintable","office"]],["drone","Drone","assets/weapons/drone.png",["tech","remote","surveillance","modern","powered","mobile","black","fragile"]],["gold_dumbbell","Gold Dumbbell","assets/weapons/gold_dumbbell.png",["blunt","heavy","luxury","gym","metal","obvious","fingerprintable","decorative"]],["keycard","Keycard","assets/weapons/keycard.png",["access","tech","thin","corporate","concealable","plastic","small","everyday"]],["luxury_pen","Luxury Pen","assets/weapons/luxury_pen.png",["sharp","luxury","small","concealable","professional","metal","office","fingerprintable"]],["mangrenade_candle","Mangrenade Candle","assets/weapons/mangreneade_candle.png",["fire","brand","collectible","decorative","small","luxury","everyday","fragile"]],["marble_bust","Marble Bust","assets/weapons/marble_bust.PNG",["blunt","heavy","decorative","luxury","art","solid","fingerprintable","office"]],["mci_original_artwork","MCI Original Artwork","assets/weapons/mci_original_artwork.PNG",["collectible","art","decorative","valuable","fragile","brand","luxury","office"]],["ring_light_stand","Ring Light Stand","assets/weapons/ring_light_stand.png",["metal","creative","tech","long","studio","portable","fingerprintable","blunt"]],["smart_speaker","Smart Speaker","assets/weapons/smart_speaker.png",["tech","powered","black","blunt","small","wired","everyday","office"]],["smart_watch_cable","Smart Watch Cable","assets/weapons/smart_watch_cable.png",["tech","flexible","small","everyday","concealable","cord","wired","modern"]],["sous_vide_weight","Sous Vide Weight","assets/weapons/sous_vide_weight.png",["heavy","kitchen","metal","blunt","professional","small","fingerprintable","practical"]],["stiletto","Stiletto","assets/weapons/stiletto.png",["sharp","fashion","concealable","luxury","personal","handheld","small","fingerprintable"]],["vr_headset","VR Headset","assets/weapons/vr_headset.png",["tech","modern","black","recreational","powered","headset","fragile","everyday"]]],
motives:[["affair","Affair","assets/motives/affair.png",["romantic","secret","personal","impulsive","status","emotional","shame","risk"]],["blackmail","Blackmail","assets/motives/blackmail.png",["secret","control","planned","fear","money","leverage","long-term","corporate"]],["career","Career","assets/motives/career.png",["professional","ambition","status","planned","reputation","competitive","long-term","public"]],["cover_up","Cover Up","assets/motives/cover_up.png",["secret","planned","protective","corporate","fear","control","reputation","long-term"]],["debt_pressure","Debt Pressure","assets/motives/debt_pressure.png",["financial","desperate","pressure","fear","short-term","risk","long-term","control"]],["family_secret","Family Secret","assets/motives/family_secret.png",["family","secret","protective","long-term","shame","emotional","reputation","fear"]],["financial_ruin","Financial Ruin","assets/motives/financial_ruin.png",["financial","desperate","status","fear","collapse","planned","public","reputation"]],["inheritance","Inheritance","assets/motives/inheritance.png",["family","financial","planned","status","long-term","greed","secret","control"]],["jealousy","Jealousy","assets/motives/jealousy.png",["romantic","emotional","impulsive","status","personal","resentment","public","shame"]],["mistaken_id","Mistaken Identity","assets/motives/mistaken_id.png",["error","confusion","impulsive","bad intel","accidental","opportunistic","fear","short-term"]],["obsession","Obsession","assets/motives/obsession.png",["romantic","fixated","emotional","long-term","irrational","personal","secret","control"]],["professional_rivalry","Professional Rivalry","assets/motives/professional_rivalry.png",["professional","status","competition","ambition","reputation","planned","long-term","public"]],["rejection","Rejection","assets/motives/rejection.png",["romantic","emotional","impulsive","personal","humiliation","resentment","status","shame"]],["reputation_protection","Reputation Protection","assets/motives/reputation_protection.png",["status","reputation","protective","planned","public","fear","professional","control"]],["revenge","Revenge","assets/motives/revenge.png",["resentment","justice","planned","personal","long-term","emotional","secret","control"]],["whistleblower_silence","Whistleblower Silence","assets/motives/whistleblower_silence.png",["corporate","secret","planned","protective","reputation","fear","professional","control"]]]};
const CASES=[{id:"MCI-001",victim:"Velvet Kane",victimImg:"assets/suspects/velvet_kane.JPG",title:"The Better Model",turns:6,solution:{suspect:"dorian_luxe",weapon:"marble_bust",room:"art_vault",motive:"professional_rivalry"},brief:"Velvet Kane has been found dead inside Blackwood Tower. Evidence suggests a confrontation took place shortly before her death. Identify the murderer, weapon, room and motive.",den:"Dorian Luxe murdered Velvet Kane. The confrontation took place inside the Art Vault. During the argument Dorian used the Marble Bust as an improvised weapon. The motive was Professional Rivalry."},{id:"MCI-002",victim:"Otis Blank",victimImg:"assets/suspects/otis_blank.JPG",title:"Dead Air",turns:6,solution:{suspect:"milo_vale",weapon:"smart_speaker",room:"podstudio",motive:"cover_up"},brief:"Otis Blank has been found dead after hours inside Blackwood Tower. The first report mentions locked doors, recorded audio and a technical system that should not have been running.",den:"Milo Vale murdered Otis Blank in the Podcast Studio. The Smart Speaker was used as part of the method. The motive was Cover Up. Otis knew too much and Milo chose silence over exposure."},{id:"MCI-003",victim:"India Gold",victimImg:"assets/suspects/India_gold.JPG",title:"A View From Above",turns:6,solution:{suspect:"saffron_skye",weapon:"champagne_sabre",room:"rooftop",motive:"blackmail"},brief:"India Gold has been found dead at Blackwood Tower. Witness statements place several residents near the upper floors shortly before midnight. The evidence points to leverage, fear and a private confrontation.",den:"Saffron Skye murdered India Gold on the Rooftop using the Champagne Sabre. India had information Saffron could not allow to surface. The motive was Blackmail."}];
let state={screen:"home",caseIndex:0,guessesLeft:6,selected:{},locked:{},wrong:{},revealed:{},evidence:{suspect:[],weapon:[],room:[],motive:[]},feedback:[],history:[],lastScore:null};let scrollMemory={};const player={rank:localStorage.getItem("mci_rank")||"Detective",streak:+(localStorage.getItem("mci_streak")||0),solved:+(localStorage.getItem("mci_solved")||0)};const currentCase=()=>CASES[state.caseIndex];
function haptic(p=10){if(navigator.vibrate)navigator.vibrate(p)}function bg(p){return `style="background-image:url('${p}')"`}function saveScrolls(){document.querySelectorAll(".carousel").forEach(e=>scrollMemory[e.dataset.type]=e.scrollLeft)}function restoreScrolls(){requestAnimationFrame(()=>document.querySelectorAll(".carousel").forEach(e=>{if(scrollMemory[e.dataset.type]!=null)e.scrollLeft=scrollMemory[e.dataset.type];if(state.selected[e.dataset.type]){const c=e.querySelector(`[data-card-id="${state.selected[e.dataset.type]}"]`);if(c)c.scrollIntoView({inline:"center",block:"nearest",behavior:"smooth"})}}))}function updateLiveCards(){document.querySelectorAll(".carousel").forEach(car=>{const mid=car.getBoundingClientRect().left+car.clientWidth/2;let best=null,dist=Infinity;car.querySelectorAll(".card").forEach(card=>{card.classList.remove("live");const r=card.getBoundingClientRect();const d=Math.abs((r.left+r.width/2)-mid);if(d<dist){dist=d;best=card}});if(best)best.classList.add("live")})}
function render(){saveScrolls();if(state.screen==="home")home();if(state.screen==="casefile")casefile();if(state.screen==="investigation")investigation();if(state.screen==="solved")end(false);if(state.screen==="failed")end(true);restoreScrolls()}
function home(){app.innerHTML=`<section class="screen" ${bg(ASSETS.frontpage)}><div class="content"><h1>MCI</h1><h2>MURDER CASE INVESTIGATION</h2><div class="statgrid"><div class="stat"><div class="label">Rank</div><div class="value">${player.rank}</div></div><div class="stat"><div class="label">Streak</div><div class="value">${player.streak}</div></div><div class="stat"><div class="label">Solved</div><div class="value">${player.solved}</div></div></div><div class="panel"><h2>MVP DAILY FLOW</h2><div class="case-list">${CASES.map((c,i)=>`<div class="case-pill ${i<state.caseIndex?'done':''}"><b>${c.id}</b><br>${c.title}</div>`).join("")}</div></div><button class="primary" onclick="openCase()">OPEN CASE FILE</button><button class="secondary" onclick="alert('Information Base comes next')">INFORMATION BASE</button></div></section>`}
function openCase(){resetForCase(state.caseIndex);go("casefile")}function resetForCase(i){state={...state,caseIndex:i,guessesLeft:CASES[i].turns,selected:{},locked:{},wrong:{},revealed:{},evidence:{suspect:[],weapon:[],room:[],motive:[]},feedback:[],history:[],lastScore:null};scrollMemory={}}
function casefile(){const c=currentCase();app.innerHTML=`<section class="screen" ${bg(ASSETS.casefile)}><div class="content"><div class="panel"><h2>VICTIM FILE OPENED</h2><h2>${c.victim}</h2><h3>${c.id} — ${c.title}</h3><p>${c.brief}</p><h2>${c.turns} accusations authorised</h2></div><button class="primary" onclick="go('investigation')">BEGIN INVESTIGATION</button></div></section>`}
function investigation(){const c=currentCase();app.innerHTML=`<div class="fixedhud"><div class="hudrow"><div>${player.rank}</div><div>${c.id}</div><div>${state.guessesLeft} left</div></div><div class="theory">Murderer: ${name("suspects",state.selected.suspect)} | Weapon: ${name("weapons",state.selected.weapon)} | Room: ${name("rooms",state.selected.room)} | Motive: ${name("motives",state.selected.motive)} | ${Object.keys(state.locked).length}/4 locked</div></div><section class="screen investigation" ${bg(ASSETS.investigation)}><div class="content">${progressHTML()}${evidenceBoard()}${carousel("suspect","MURDERER",CARDS.suspects)}${carousel("weapon","WEAPON",CARDS.weapons)}${carousel("room","ROOM",CARDS.rooms)}${carousel("motive","MOTIVE",CARDS.motives)}${feedbackHTML()}<div class="panel"><h2>MAKE ACCUSATION</h2><p>Select one murderer, weapon, room and motive.</p><button class="primary" onclick="accuse()">SUBMIT ACCUSATION</button></div></div></section>`;setTimeout(updateLiveCards,50)}
function evidenceBoard(){const labels={suspect:"CHARACTERISTICS",weapon:"WEAPON FEATURES",room:"ROOM FEATURES",motive:"DRIVERS"};return `<div class="panel"><h2>EVIDENCE BOARD</h2><div class="evidence-board">${["suspect","weapon","room","motive"].map(k=>`<div class="evidence-box"><h4>${labels[k]}</h4>${state.evidence[k].length?state.evidence[k].map(x=>`<span class="evidence-tag">${x}</span>`).join(""):"<span class='evidence-tag'>Awaiting evidence</span>"}</div>`).join("")}</div></div>`}
function progressHTML(){if(!state.lastScore)return "";const pct=[0,25,50,75,100][state.lastScore];const col=["var(--red)","var(--amber1)","var(--amber2)","var(--amber3)","var(--green)"][state.lastScore];return `<div class="panel"><div class="progress-label">${state.lastScore}/4 CATEGORIES MATCH</div><div class="progress-shell"><div class="progress-bar" style="width:${pct}%;background:${col}"></div></div></div>`}
function carousel(type,title,items){const loop=[...items,...items,...items];return `<div class="carousel-block"><div class="carousel-title">${title}</div><div class="carousel" data-type="${type}" onscroll="loopCarousel(this);updateLiveCards()">${loop.map(item=>card(type,item)).join("")}</div></div>`}
function card(type,item){const[id,n,img,traits]=item;const cls=[state.selected[type]===id?"selected":"",state.locked[type]===id?"correct":"",state.wrong[type]?.includes(id)?"incorrect":""].join(" ");const contain=id==="marble_bust"?"contain":"";return `<div class="card ${cls}" data-card-id="${id}" onclick="selectCard('${type}','${id}')"><img class="${contain}" src="${img}" onerror="this.style.opacity=.15"><div class="card-name">${n}</div><div class="traits">${traits.slice(0,8).map(t=>`<span class="trait ${isRev(type,id,t)?"revealed":""}">${t}</span>`).join("")}</div></div>`}
function selectCard(type,id){if(state.locked[type])return;haptic(10);state.selected[type]=id;render()}function accuse(){const keys=["suspect","weapon","room","motive"],c=currentCase();if(!keys.every(k=>state.selected[k])){haptic([20,50,20]);alert("Select one murderer, weapon, room and motive.");return}haptic(25);state.feedback=[];let correct=0;const row=[];keys.forEach(k=>{const guess=state.selected[k],sol=c.solution[k],ok=guess===sol;row.push(ok);if(ok)correct++;if(ok){state.locked[k]=guess;state.feedback.push({type:k,ok:true,name:item(k,guess)[1]});haptic([25,45,25])}else{state.wrong[k]=state.wrong[k]||[];if(!state.wrong[k].includes(guess))state.wrong[k].push(guess);const matches=item(k,guess)[3].filter(t=>item(k,sol)[3].includes(t));const disclosed=matches[0]||"none";state.revealed[k]=state.revealed[k]||{};state.revealed[k][guess]=state.revealed[k][guess]||[];if(disclosed!=="none"&&!state.revealed[k][guess].includes(disclosed))state.revealed[k][guess].push(disclosed);if(disclosed!=="none"&&!state.evidence[k].includes(disclosed))state.evidence[k].push(disclosed);state.feedback.push({type:k,ok:false,name:item(k,guess)[1],disclosed,hidden:Math.max(matches.length-(matches.length?1:0),0)})}});state.history.push(row);state.lastScore=correct;state.guessesLeft--;if(correct===4){player.solved++;player.streak++;localStorage.setItem("mci_solved",player.solved);localStorage.setItem("mci_streak",player.streak);haptic([60,90,60]);go("solved");return}if(state.guessesLeft<=0){haptic([100,100,100]);go("failed");return}render()}
function feedbackHTML(){if(!state.feedback.length)return"";return `<div class="panel"><h2>EVIDENCE FEEDBACK</h2>${state.feedback.map(f=>{if(f.ok)return `<div class="feedback-card correct"><h3>${f.type.toUpperCase()}</h3><p>${f.name}</p><p class="green">CONFIRMED</p></div>`;const w=f.type==="suspect"?"characteristic":f.type==="motive"?"driver":"feature";return `<div class="feedback-card"><h3>${f.type.toUpperCase()}</h3><p>${f.name}</p><p class="green">${f.disclosed}</p><p>${f.hidden} additional ${w}${f.hidden===1?"":"s"} match.</p></div>`}).join("")}</div>`}
function end(failed){const c=currentCase(),s=c.solution;app.innerHTML=`<section class="screen" ${bg(ASSETS.caseclosed)}><div class="content"><div class="end-title">${failed?"THEY GOT AWAY WITH IT":"CASE SOLVED"}</div><div class="subtitle">${failed?"The killer walks free.":"Great work, Detective."}</div><div class="panel"><h2>VICTIM: ${c.victim}</h2><div class="result-grid">${res("MURDERER","suspect",s.suspect)}${res("WEAPON","weapon",s.weapon)}${res("ROOM","room",s.room)}${res("MOTIVE","motive",s.motive)}</div><h2>RECONSTRUCTION</h2><p>${highlight(c.den)}</p><button class="primary" onclick="share(${failed})">SHARE RESULT</button>${state.caseIndex<CASES.length-1?`<button class="secondary" onclick="nextCase()">NEXT MVP DAY</button>`:`<button class="secondary" onclick="go('home')">RETURN HOME</button>`}</div></div></section>`}
function res(label,type,id){const it=item(type,id);return `<div class="result-card"><img class="${id==="marble_bust"?"contain":""}" src="${it[2]}"><h2>${label}</h2><p>${it[1]}</p></div>`}function highlight(txt){const c=currentCase(),s=c.solution;[item("suspect",s.suspect)[1],item("weapon",s.weapon)[1],item("room",s.room)[1],item("motive",s.motive)[1]].forEach(w=>{txt=txt.replaceAll(w,`<mark>${w}</mark>`)});return txt}function share(failed){const c=currentCase(),used=c.turns-state.guessesLeft,grid=state.history.map(r=>r.map(x=>x?"🟩":"⬛").join("")).join("\n")||"⬛⬛⬛⬛";const text=`${c.id}\n\n${grid}\n\n${failed?"They got away with it.":`Solved in ${used} accusation${used===1?"":"s"}.`}\nRank: ${player.rank}\nhttps://mancave-industries.github.io/MCI_Muder_Case_Investigation-/`;if(navigator.share)navigator.share({text});else{navigator.clipboard.writeText(text);alert("Result copied.")}}function nextCase(){state.caseIndex++;resetForCase(state.caseIndex);go("casefile")}function go(x){state.screen=x;render()}function item(type,id){return({suspect:CARDS.suspects,weapon:CARDS.weapons,room:CARDS.rooms,motive:CARDS.motives}[type]).find(x=>x[0]===id)}function name(group,id){if(!id)return"Not selected";return({suspects:CARDS.suspects,weapons:CARDS.weapons,rooms:CARDS.rooms,motives:CARDS.motives}[group]).find(x=>x[0]===id)?.[1]||"Not selected"}function isRev(type,id,t){return state.revealed?.[type]?.[id]?.includes(t)}function loopCarousel(el){const third=el.scrollWidth/3;if(el.scrollLeft<third*.25)el.scrollLeft+=third;if(el.scrollLeft>third*1.75)el.scrollLeft-=third;scrollMemory[el.dataset.type]=el.scrollLeft}render();
